#!/bin/bash
"..//, .//, 100-lets_move, 101-clean_emacs, 102-tree, 103-commas, 10-back, 11-lists, 12-file_type, 13-symbolic_link, 14-copy_html, 2-bring_me_home, school.mgc, 0-current_working_directory, README.md, 8-firstdelete, 9-firstdirdeletion, 6-firstdirectory, 3-listfiles, 5-listfilesdigitonly, 1-listit, 4-listmorefiles, 7-movethatfile, ls, "
